### ISSUE TITLE
Some MD files are encoded as UTF-8-BOM and are ignored by Jekyll

### ISSUE THREAD

**Issue by mamintoosi** [cpp-tutor/learnmoderncpp-tutorial#3]
Dear Richard, thank you, for creating this wonderful course on modern C++. I have learned a lot from it and I appreciate your generosity in sharing it with the world. I have forked your repository, and I am modifying it to suit my own needs and preferences. I have also created a GitHub Pages website for it using the Jekyll site generator and the just-the-docs template. You can check it out here: https://fum-cs.github.io/modern-cpp/. 

I encountered a problem where some of the markdown files (01 - 04) were not rendered by Jekyll. I discovered that it was because these files were encoded as UTF-8-BOM, which Jekyll ignored. I converted the encoding of these files to UTF-8 using Notepad++, and the problem was fixed.

**Comment by cpp-tutor** [comment]
Thanks for the report, I've now removed the BOM from the affected files you describe (also 08). Checking out your site, it looks very nice! If you do make substantial corrections/additions, feel free to submit a pull request.
